name: Generate-Documentation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches:
      - master
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Generate Module Documents
        shell: pwsh
        run: |
          Import-Module .\Documentation\Export-ModuleDocs.ps1; Get-ChildItem -Directory -Exclude .github | ForEach-Object {
            Export-ModuleDocs -Path $_ -ModulePrefix 'PSVault' -DescriptionFile '' -Prune -Version $([double]((get-content $_\README.md | select-string "Help Version") -replace "^.{14}") + 0.1) 
          };

      - name: Generate Repository Documents
        shell: pwsh
        run: |
          Import-Module .\Documentation\Compile-ModuleDocs.ps1; Compile-ModuleDocs -Path .\ -OutFile .\READNE.md; 
